name: Build Extension

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check licenses
      run: npm run license-check

    - name: Lint code
      run: npm run lint

    - name: Compile TypeScript
      run: npm run compile

    - name: Run tests
      run: |
        xvfb-run -a npm test
      if: runner.os == 'Linux'

    - name: Install vsce (VS Code Extension Manager)
      run: npm install -g @vscode/vsce

    - name: Build (webpack production)
      run: npm run webpack:prod

    - name: Package extension
      run: vsce package

    - name: Get package info
      run:  vsce ls --tree

    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: fab-inspector-extension
        path: '*.vsix'
        retention-days: 30